return {
  'folke/zen-mode.nvim',
  lazy = false,
  opts = {
    window = {
      width = 0.6,
      options = {
        wrap = true,
        linebreak = true,
        number = true,
        relativenumber = true,
      },
    },
    on_open = function()
      vim.o.showtabline = 2 -- always show tab bar
    end,
    on_close = function()
      vim.o.showtabline = 2 -- keep it visible after closing, too
    end,
  },
  keys = {
    {
      '<leader>z',
      function()
        require('zen-mode').toggle()
      end,
      desc = 'Toggle Zen Mode',
    },
  },
  config = function(_, opts)
    require('zen-mode').setup(opts)

    local vault = vim.fs.normalize(vim.fn.expand '~/Vault')
    local function open_for_vault_note(buf)
      if not vim.api.nvim_buf_is_valid(buf) or vim.b[buf].vault_zen_initialized then
        return
      end

      local path = vim.fs.normalize(vim.api.nvim_buf_get_name(buf))
      if vim.bo[buf].filetype ~= 'markdown' or (path ~= vault and not vim.startswith(path, vault .. '/')) then
        return
      end

      -- Mark first so the BufEnter generated by opening Zen cannot recurse.
      -- It also lets a manual <leader>z close remain closed for this buffer.
      vim.b[buf].vault_zen_initialized = true
      vim.wo.concealcursor = ''
      vim.wo.conceallevel = 2
      require('zen-mode').open()
    end

    vim.api.nvim_create_autocmd('BufEnter', {
      callback = function(args)
        vim.schedule(function()
          open_for_vault_note(args.buf)
        end)
      end,
    })

    -- Plugin setup can happen after the initial buffer's BufEnter event.
    vim.schedule(function()
      open_for_vault_note(vim.api.nvim_get_current_buf())
    end)
  end,
}
